name: Update ASCII Pet

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:      # ручной запуск

permissions: 
  contents: write    # чтобы пушить pet.svg


jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Github CLI
        run: sudo apt-get install gh

      - name: Generate pet.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python generate_pet.py

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git add pet.svg
          git diff --stage --quiet || git commit -m "обновлён питомец"
          git push
